[workspace]
members = [
    "cli",
    "dailyboj_api",
    "filedriver",
    "management-tool",
    "route_path",
    "service_macro",
    "shaped",
    "swaggering",
]

[profile.dev.package."*"]
opt-level = 2
